### ISSUE TITLE
The Spark Context code does not correctly detect a failed Spark Job

### ISSUE THREAD

**Issue by pferrel** [actionml/harness#116]
There seem to be many cases where the creation of a SparkContext errors out so that the Spark Job is not created. Therefore the Spark Job does not create an error so the `harness train` never errors. 

This causes the queued job to stay queued forever so that fixing the error is futile since a new job will never be run.

ALL conditions that fail to start a Spark Job OR cause the Job to return an error should dequeue the Harness JobManager job. This will allow for fixing the problem and re-executing `harness train ...`

**Comment by andreyshikov** [comment]
@pferrel please take a look at #117
