### ISSUE TITLE
item based recs return the item itself

### ISSUE THREAD

**Issue by pferrel** [actionml/harness#132]
item-based recs should return the item itself only when configured to do so. Probably a missed `mustNot` value

add to integration test

**Comment by pferrel** [comment]
This is true of item-set queries too, the default should be to exclude the item or item-set items from results unless `returnSelf` is true in the query.

**Comment by BernhardHH** [comment]
It seems that the item is included in the blacklist (and excluded from results) if returnSelf is set to true. Which seems to be the default now:

val queryBlacklistWithItem = if(query.item.isDefined && query.returnSelf.getOrElse(true)) { // item-based and not returnSelf

but in the docs, it is still "false":

 **returnSelf**: optional boolean asking to include the item that was part of the query (if there was one) as part of the results. Defaults to false.
