### ISSUE TITLE
SSL Support for MongoDB connection

### ISSUE THREAD

**Issue by xw-mon** [actionml/harness#148]
I tried to use Azure Cosmos DB as alternative for MongoDB for harness. CosmosDB uses SSL and authentication by default which is not supported in harness yet.

Error Message:
`No SSL support in java.nio.channels.AsynchronousSocketChannel. For SSL support use com.mongodb.connection.netty.NettyStreamFactoryFactory`
See attached log file
[harness-mongodb-ssl-error.txt](https://github.com/actionml/harness/files/3161324/harness-mongodb-ssl-error.txt)

Please change the mongodb driver to support SSL connections.

**Comment by pferrel** [comment]
@andreyshikov is this fixed with the URI changes in 0.5.0?

**Comment by andreyshikov** [comment]
yes, it works now
