### ISSUE TITLE
Harness fails with mongodb authentication

### ISSUE THREAD

**Issue by nl-mondia** [actionml/harness#157]
We are using harness server container to attach to authenticated Mongo DB.

We have tried multiple variations with sparkConf like:

#1
    "spark.mongodb.input.uri": "mongodb://username:password@hostname.domain.tld/",
    "spark.mongodb.input.database": "database-name",
    "spark.mongodb.input.collection": "items",
    "spark.mongodb.input.readPreference.name": "primaryPreferred"
#2     "spark.mongodb.input.uri":"mongodb://username:password@hostname.domain.tld:27017/database-name/?authSource=database-name",
    "spark.mongodb.output.uri":"mongodb://username:password@hostname.domain.tld:27017/database-name/?authSource=database-name",
#3
    "spark.mongodb.input.uri":"mongodb://username:password@hostname.domain.tld:27017/database-name",
    "spark.mongodb.output.uri":"mongodb://username:password@hostname.domain.tld:27017/database-name"

But whenever we start training we are getting the same error  : 
**WARNING: Partitioning failed.
Partitioning using the 'DefaultMongoPartitioner$' failed.
com.mongodb.MongoException: host and port should be specified in host:port format
	at com.mongodb.ServerAddress.<init>(ServerAddress.java:123)
	at com.mongodb.internal.connection.ServerAddressHelper.createServerAddress(ServerAddressHelper.java:33)
	at com.mongodb.internal.connection.ServerAddressHelper.createServerAddress(ServerAddressHelper.java:26)**

We are not getting this error when we use database without authentication.

Google groups thread : https://groups.google.com/forum/#!topic/actionml-user/kqOF0tLO0o0

Thanks,
Nikola

**Comment by pferrel** [comment]
@andreyshikov is this fixed with the URI change in 0.5.0?

**Comment by andreyshikov** [comment]
> @andreyshikov is this fixed with the URI change in 0.5.0?

yes
