### ISSUE TITLE
 spark running error : ERROR Inbox: Ignoring error java.io.EOFException

### ISSUE THREAD

**Issue by zhuchaowe** [actionml/harness#158]
Spark Executor Command: "/usr/lib/jvm/java-1.8-openjdk/jre/bin/java" "-cp" "///conf:/spark/jars/*" "-Xmx2048M" "-Dspark.driver.port=44603" "org.apache.spark.executor.CoarseGrainedExecutorBackend" "--driver-url" "spark://CoarseGrainedScheduler@ff059f403060:44603" "--executor-id" "1" "--hostname" "172.29.0.5" "--cores" "2" "--app-id" "app-20190625031854-0000" "--worker-url" "spark://Worker@172.29.0.5:37435"
========================================

Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
19/06/25 03:18:59 INFO CoarseGrainedExecutorBackend: Started daemon with process name: 57@aae27ca361b0
19/06/25 03:18:59 INFO SignalUtils: Registered signal handler for TERM
19/06/25 03:18:59 INFO SignalUtils: Registered signal handler for HUP
19/06/25 03:18:59 INFO SignalUtils: Registered signal handler for INT
19/06/25 03:19:02 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
19/06/25 03:19:03 INFO SecurityManager: Changing view acls to: root
19/06/25 03:19:03 INFO SecurityManager: Changing modify acls to: root
19/06/25 03:19:03 INFO SecurityManager: Changing view acls groups to: 
19/06/25 03:19:03 INFO SecurityManager: Changing modify acls groups to: 
19/06/25 03:19:03 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with modify permissions: Set()
19/06/25 03:19:05 INFO TransportClientFactory: Successfully created connection to ff059f403060/172.29.0.2:44603 after 408 ms (0 ms spent in bootstraps)
19/06/25 03:19:06 INFO SecurityManager: Changing view acls to: root
19/06/25 03:19:06 INFO SecurityManager: Changing modify acls to: root
19/06/25 03:19:06 INFO SecurityManager: Changing view acls groups to: 
19/06/25 03:19:06 INFO SecurityManager: Changing modify acls groups to: 
19/06/25 03:19:06 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with modify permissions: Set()
19/06/25 03:19:06 INFO TransportClientFactory: Successfully created connection to ff059f403060/172.29.0.2:44603 after 5 ms (0 ms spent in bootstraps)
19/06/25 03:19:06 INFO DiskBlockManager: Created local directory at /tmp/spark-21895064-184b-4817-9988-c7e05776cbe8/executor-4423d906-96fc-4abc-a1ec-896b4b944506/blockmgr-58f7f70a-975f-465c-8dd5-a3473462f140
19/06/25 03:19:06 INFO MemoryStore: MemoryStore started with capacity 912.3 MB
19/06/25 03:19:07 INFO CoarseGrainedExecutorBackend: Connecting to driver: spark://CoarseGrainedScheduler@ff059f403060:44603
19/06/25 03:19:07 INFO WorkerWatcher: Connecting to worker spark://Worker@172.29.0.5:37435
19/06/25 03:19:07 INFO TransportClientFactory: Successfully created connection to /172.29.0.5:37435 after 11 ms (0 ms spent in bootstraps)
19/06/25 03:19:07 INFO WorkerWatcher: Successfully connected to spark://Worker@172.29.0.5:37435
19/06/25 03:19:07 INFO CoarseGrainedExecutorBackend: Successfully registered with driver
19/06/25 03:19:07 INFO Executor: Starting executor ID 1 on host 172.29.0.5
19/06/25 03:19:08 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 40379.
19/06/25 03:19:08 INFO NettyBlockTransferService: Server created on 172.29.0.5:40379
19/06/25 03:19:08 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
19/06/25 03:19:08 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(1, 172.29.0.5, 40379, None)
19/06/25 03:19:08 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(1, 172.29.0.5, 40379, None)
19/06/25 03:19:08 INFO BlockManager: Initialized BlockManager: BlockManagerId(1, 172.29.0.5, 40379, None)
19/06/25 03:19:08 ERROR Inbox: Ignoring error
java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:197)
	at java.io.DataInputStream.readUTF(DataInputStream.java:609)
	at java.io.DataInputStream.readUTF(DataInputStream.java:564)
	at org.apache.spark.scheduler.TaskDescription$$anonfun$decode$1.apply(TaskDescription.scala:134)
	at org.apache.spark.scheduler.TaskDescription$$anonfun$decode$1.apply(TaskDescription.scala:133)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at org.apache.spark.scheduler.TaskDescription$.decode(TaskDescription.scala:133)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$$anonfun$receive$1.applyOrElse(CoarseGrainedExecutorBackend.scala:96)
	at org.apache.spark.rpc.netty.Inbox$$anonfun$process$1.apply$mcV$sp(Inbox.scala:117)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:205)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:101)
	at org.apache.spark.rpc.netty.Dispatcher$MessageLoop.run(Dispatcher.scala:221)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by pnutmath** [comment]
What is resolution for this error you applied? @zhuchaowe
