### ISSUE TITLE
MongoDB indexes not being created

### ISSUE THREAD

**Issue by IsidroGH** [actionml/harness#160]
I tried with Harness 0.4.0 & 0.5.0 and MongoDB indexes are not being created when a new UR engine is added. 

I debugged the code and the method `createIndexes` is never executed in `URDataset.init` or `MongoStore` because `ttl` is always `None`.

I had to set a value for ttl in the ur-engine.json to have the indexes created. But if someone doesn't want a ttl as me, indexes won't be created.

**Comment by pferrel** [comment]
We are actively working on index updating. Some fixes will be in 0.5.1
