### ISSUE TITLE
MongoAsyncDao - Sync DAO error after Spark Job finished

### ISSUE THREAD

**Issue by abinder-1** [actionml/harness#205]
# General Setup
* System: Ubuntu 18.04.3 LTS
* Using docker-compose as described [here](https://actionml.com/docs/harness_container_guide).

# Steps
* ```docker-compose exec harness-cli bash -c 'harness-cli add data/my-engine-config.json'``` (see Config)
* call the REST API to generate some events (harness log and response looks fine)
* call the REST API to train the model (Job finished, but MongoAsyncDao threw Exception)
* call the REST API to query user/item (harness log and response looks fine)

# Config
```
{
    "engineId": "retailrocket",
    "engineFactory": "com.actionml.engines.ur.UREngine",
    "sparkConf": {
        "master": "local",
        "spark.serializer": "org.apache.spark.serializer.KryoSerializer",
        "spark.kryo.registrator": "org.apache.mahout.sparkbindings.io.MahoutKryoRegistrator",
        "spark.kryo.referenceTracking": "false",
        "spark.kryoserializer.buffer": "300m",
        "spark.executor.memory": "1g",
        "spark.driver.memory": "1g",
        "spark.es.index.auto.create": "true",
        "spark.es.nodes": "<my_ip_adress>:9200",
        "spark.es.nodes.wan.only": "true"
    },
    "algorithm":{
        "indicators": [
            {
                "name": "transaction"
            },{
                "name": "view"
            },{
                "name": "addtocart"
            }
        ]
    }
}
```

# Log Output

```10:03:40.551 INFO  ContextCleaner    - Cleaned accumulator 5316
10:03:40.561 INFO  ContextCleaner    - Cleaned accumulator 5556
10:03:40.561 INFO  ContextCleaner    - Cleaned accumulator 5452
10:03:40.561 INFO  ContextCleaner    - Cleaned accumulator 5386
10:03:40.561 INFO  ContextCleaner    - Cleaned accumulator 5500
10:03:40.561 INFO  ContextCleaner    - Cleaned accumulator 5476
10:03:40.617 INFO  Executor          - Finished task 0.0 in stage 143.0 (TID 59). 1181 bytes result sent to driver
10:03:40.619 INFO  TaskSetManager    - Finished task 0.0 in stage 143.0 (TID 59) in 1243 ms on localhost (executor driver) (1/1)
10:03:40.619 INFO  TaskSchedulerImpl - Removed TaskSet 143.0, whose tasks have all completed, from pool
10:03:40.621 INFO  DAGScheduler      - ResultStage 143 (runJob at EsSpark.scala:108) finished in 1.267 s
10:03:40.625 INFO  DAGScheduler      - Job 31 finished: runJob at EsSpark.scala:108, took 1.282262 s
10:03:40.803 INFO  SparkContextSupport$ - Job f3f1f145-e4f9-44dd-a713-28587fa076d5 completed in 1573121020802 ms [engine retailrocket]
10:03:40.806 INFO  AbstractConnector - Stopped Spark@6454a6a2{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
10:03:40.813 INFO  SparkUI           - Stopped Spark web UI at http://f4f9bbcb5baa:4040
10:03:40.816 ERROR MongoAsyncDao     - Can't removeOne from collection harness_meta_store.jobs with filter WrappedArray((jobId,Equals(f3f1f145-e4f9-44dd-a713-28587fa076d5)))
10:03:40.818 ERROR MongoAsyncDao     - Sync DAO error
java.lang.RuntimeException: Can't removeOne from collection harness_meta_store.jobs with filter WrappedArray((jobId,Equals(f3f1f145-e4f9-44dd-a713-28587fa076d5)))
        at com.actionml.core.store.backends.MongoAsyncDao$$anonfun$removeOneAsync$1.apply(MongoAsyncDao.scala:135)
        at com.actionml.core.store.backends.MongoAsyncDao$$anonfun$removeOneAsync$1.apply(MongoAsyncDao.scala:129)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
10:03:40.820 ERROR AsyncEventQueue   - Listener JobManagerListener threw an exception
java.lang.RuntimeException: Can't removeOne from collection harness_meta_store.jobs with filter WrappedArray((jobId,Equals(f3f1f145-e4f9-44dd-a713-28587fa076d5)))
        at com.actionml.core.store.backends.MongoAsyncDao$$anonfun$removeOneAsync$1.apply(MongoAsyncDao.scala:135)
        at com.actionml.core.store.backends.MongoAsyncDao$$anonfun$removeOneAsync$1.apply(MongoAsyncDao.scala:129)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
10:03:40.824 INFO  MapOutputTrackerMasterEndpoint - MapOutputTrackerMasterEndpoint stopped!
10:03:40.851 INFO  MemoryStore       - MemoryStore cleared
10:03:40.851 INFO  BlockManager      - BlockManager stopped
10:03:40.853 INFO  BlockManagerMaster - BlockManagerMaster stopped
10:03:40.854 INFO  OutputCommitCoordinator$OutputCommitCoordinatorEndpoint - OutputCommitCoordinator stopped!
10:03:40.865 INFO  SparkContext      - Successfully stopped SparkContext
10:03:41.397 INFO  MongoClientCache  - Closing MongoClient: [mongo:27017]
10:03:41.400 INFO  connection        - Closed connection [connectionId{localValue:34, serverValue:34}] to mongo:27017 because the pool has been closed.```

**Comment by andreyshikov** [comment]
> # General Setup
> * System: Ubuntu 18.04.3 LTS
> * Using docker-compose as described [here](https://actionml.com/docs/harness_container_guide).
> 
> # Steps
> * `docker-compose exec harness-cli bash -c 'harness-cli add data/my-engine-config.json'` (see Config)
> * call the REST API to generate some events (harness log and response looks fine)
> * call the REST API to train the model (Job finished, but MongoAsyncDao threw Exception)
> * call the REST API to query user/item (harness log and response looks fine)
> 
> # Config
> ```
> {
>     "engineId": "retailrocket",
>     "engineFactory": "com.actionml.engines.ur.UREngine",
>     "sparkConf": {
>         "master": "local",
>         "spark.serializer": "org.apache.spark.serializer.KryoSerializer",
>         "spark.kryo.registrator": "org.apache.mahout.sparkbindings.io.MahoutKryoRegistrator",
>         "spark.kryo.referenceTracking": "false",
>         "spark.kryoserializer.buffer": "300m",
>         "spark.executor.memory": "1g",
>         "spark.driver.memory": "1g",
>         "spark.es.index.auto.create": "true",
>         "spark.es.nodes": "<my_ip_adress>:9200",
>         "spark.es.nodes.wan.only": "true"
>     },
>     "algorithm":{
>         "indicators": [
>             {
>                 "name": "transaction"
>             },{
>                 "name": "view"
>             },{
>                 "name": "addtocart"
>             }
>         ]
>     }
> }
> ```
> 
> # Log Output
> ```
> 10:03:40.561 INFO  ContextCleaner    - Cleaned accumulator 5556
> 10:03:40.561 INFO  ContextCleaner    - Cleaned accumulator 5452
> 10:03:40.561 INFO  ContextCleaner    - Cleaned accumulator 5386
> 10:03:40.561 INFO  ContextCleaner    - Cleaned accumulator 5500
> 10:03:40.561 INFO  ContextCleaner    - Cleaned accumulator 5476
> 10:03:40.617 INFO  Executor          - Finished task 0.0 in stage 143.0 (TID 59). 1181 bytes result sent to driver
> 10:03:40.619 INFO  TaskSetManager    - Finished task 0.0 in stage 143.0 (TID 59) in 1243 ms on localhost (executor driver) (1/1)
> 10:03:40.619 INFO  TaskSchedulerImpl - Removed TaskSet 143.0, whose tasks have all completed, from pool
> 10:03:40.621 INFO  DAGScheduler      - ResultStage 143 (runJob at EsSpark.scala:108) finished in 1.267 s
> 10:03:40.625 INFO  DAGScheduler      - Job 31 finished: runJob at EsSpark.scala:108, took 1.282262 s
> 10:03:40.803 INFO  SparkContextSupport$ - Job f3f1f145-e4f9-44dd-a713-28587fa076d5 completed in 1573121020802 ms [engine retailrocket]
> 10:03:40.806 INFO  AbstractConnector - Stopped Spark@6454a6a2{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
> 10:03:40.813 INFO  SparkUI           - Stopped Spark web UI at http://f4f9bbcb5baa:4040
> 10:03:40.816 ERROR MongoAsyncDao     - Can't removeOne from collection harness_meta_store.jobs with filter WrappedArray((jobId,Equals(f3f1f145-e4f9-44dd-a713-28587fa076d5)))
> 10:03:40.818 ERROR MongoAsyncDao     - Sync DAO error
> java.lang.RuntimeException: Can't removeOne from collection harness_meta_store.jobs with filter WrappedArray((jobId,Equals(f3f1f145-e4f9-44dd-a713-28587fa076d5)))
>         at com.actionml.core.store.backends.MongoAsyncDao$$anonfun$removeOneAsync$1.apply(MongoAsyncDao.scala:135)
>         at com.actionml.core.store.backends.MongoAsyncDao$$anonfun$removeOneAsync$1.apply(MongoAsyncDao.scala:129)
>         at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
>         at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
>         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:748)
> 10:03:40.820 ERROR AsyncEventQueue   - Listener JobManagerListener threw an exception
> java.lang.RuntimeException: Can't removeOne from collection harness_meta_store.jobs with filter WrappedArray((jobId,Equals(f3f1f145-e4f9-44dd-a713-28587fa076d5)))
>         at com.actionml.core.store.backends.MongoAsyncDao$$anonfun$removeOneAsync$1.apply(MongoAsyncDao.scala:135)
>         at com.actionml.core.store.backends.MongoAsyncDao$$anonfun$removeOneAsync$1.apply(MongoAsyncDao.scala:129)
>         at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
>         at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
>         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:748)
> 10:03:40.824 INFO  MapOutputTrackerMasterEndpoint - MapOutputTrackerMasterEndpoint stopped!
> 10:03:40.851 INFO  MemoryStore       - MemoryStore cleared
> 10:03:40.851 INFO  BlockManager      - BlockManager stopped
> 10:03:40.853 INFO  BlockManagerMaster - BlockManagerMaster stopped
> 10:03:40.854 INFO  OutputCommitCoordinator$OutputCommitCoordinatorEndpoint - OutputCommitCoordinator stopped!
> 10:03:40.865 INFO  SparkContext      - Successfully stopped SparkContext
> 10:03:41.397 INFO  MongoClientCache  - Closing MongoClient: [mongo:27017]
> 10:03:41.400 INFO  connection        - Closed connection [connectionId{localValue:34, serverValue:34}] to mongo:27017 because the pool has been closed.```
> ```

Hi @abinder-1 ,
Thanks for the report.
It's fixed and waiting for review https://github.com/actionml/harness/pull/204

**Comment by abinder-1** [comment]
Thank you very much for the fast response @andreyshikov!

**Comment by pferrel** [comment]
@abinder-1 is this still an issue?
