### ISSUE TITLE
All item scores are 0.0

### ISSUE THREAD

**Issue by sonyshchuk** [actionml/harness#223]
Hello,

I've used docker-compose to setup Harness + UR, went through workflow and get recommendations but all items have 0.0 scores in the result. What could go wrong?

The steps I did:
-  Docker-compose setup from https://github.com/actionml/harness-docker-compose/blob/develop/docker-compose.yml
- Create a new engine with following template: {
  "engineId": "movie_fit",
  "engineFactory": "com.actionml.engines.ur.UREngine",
  "sparkConf": {
    "es.index.auto.create": "true",
    "es.nodes": "elasticsearch",
    "es.nodes.wan.only": "true",
    "master": "local",
    "spark.driver.memory": "512m",
    "spark.es.index.auto.create": "true",
    "spark.es.nodes": "elasticsearch",
    "spark.es.nodes.wan.only": "true",
    "spark.executor.memory": "512m",
    "spark.kryo.referenceTracking": "false",
    "spark.kryo.registrator": "org.apache.mahout.sparkbindings.io.MahoutKryoRegistrator",
    "spark.kryoserializer.buffer": "300m",
    "spark.serializer": "org.apache.spark.serializer.KryoSerializer"
  },
  "returnSelf": "false",
  "algorithm":{
      "indicators": [ 
          {
            "name": "like"
          },
          {
            "name": "wish"
          },
          {
            "name": "dislike"
          },
          {
            "name": "view"
          },
          {
            "name": "like_genre"
          },
          {
            "name": "like_person"
          },
          {
            "name": "like_year"
          },
          {
            "name": "like_content_rating"
          }
      ]
  }
}
- Send events to engine. My app is the Movie app, so I generated the user+like, user+dislike events and successfully sent them to engine. Event data example:
      {
        event: "like",
        entityType: "user",
        entityId: "123",
        targetEntityType: "item",
        targetEntityId: "323",
        eventTime: date_time.iso8601
      }
- Succsessfully trained model via Rest API call. POST "<harness_host>/jobs"
- And the result is recommendations with 0.0 scores (POST "<harness_host>/queries").  This happenes regardless the requestiong recommendations for a user or just popular items.

Please assist

**Comment by pi19404** [comment]
i am also facing the same issues ,was any solution found for this
