### ISSUE TITLE
Get complete Item object from query

### ISSUE THREAD

**Issue by akhilrex** [actionml/harness#234]
Is there a way to get the complete item object as a response to the query and not just item ids?

**Comment by pferrel** [comment]
@akhilrex No. It is usually not good to use the recommender to return metadata not directly applied to recommendations. Some have expressed the desire to have image links, page links etc in the metadata and to return these arbitrary attributes with the recommendations.  I alway suggest that you save this in your metadata and use the recommended item id to look up these.
