### ISSUE TITLE
harness json file link 404 error

### ISSUE THREAD

**Issue by shishirpy** [actionml/harness#237]
The link to [harness JSON file](https://github.com/actionml/harness/blob/develop/docs/harness_json.md) in `harness/docs/engine_configuration.md` is broken.

**Comment by pferrel** [comment]
@shishirpy what is the url for the page with the link and what is the link?

**Comment by shishirpy** [comment]
I saw this on - https://actionml.com/docs/h_ur_config#configuration-sections
It mentions a `Harness JSON`, I don't see the 404 error now, but the link points the `welcome_to_actionml` page now.

**Comment by pferrel** [comment]
ok, the reference to "Harness JSON" should talk about how you can embed system environment variable in the engine's config. We decided not to document this feature and so will remove the reference.

Unless you see a need for this feature.

**Comment by pferrel** [comment]
moving to the docs repo

https://github.com/actionml/docs.actionml.com/issues/21
