### ISSUE TITLE
Mirror folder not created for new engine or imported events

### ISSUE THREAD

**Issue by AgusPietra** [actionml/harness#254]
## Description

When I want to import a batch of events, it fails because the mirror folder inside harness container doesn't exists. Of course, the events don't go to mongo neither elastic.
I know I can create it manually, but I think that, for sake of automation, it could be created with the engine or while preparing insert process.

## Error Log:

*21:08:37.510 **ERROR FSMirror**          - Engine-id: freq_purchase_together. Problem while importing saved events from /data/FreqPurchaseTogetherItems.json, exception /freq_purchase_together/20-06-11.json (No such file or directory)*

If I create a folder named /freq_purchase_together, it works fine.

## Body for engine creation

```
{
  "engineId": "freq_purchase_together",
  "engineFactory": "com.actionml.engines.ur.UREngine",
  "sparkConf": {
    "master": "local",
    "spark.driver.memory": "4g",
    "spark.executor.memory": "4g",
    "spark.es.index.auto.create": "true",
    "spark.es.nodes.wan.only": "true",
    "spark.kryo.referenceTracking": "false",
    "spark.kryo.registrator": "org.apache.mahout.sparkbindings.io.MahoutKryoRegistrator",
    "spark.kryoserializer.buffer": "300m",
    "spark.serializer": "org.apache.spark.serializer.KryoSerializer",
    "spark.testing.memory": "481859200",
    "spark.es.nodes": "elasticsearch"
  },
  "algorithm": {
    "indicators": [
      {
        "name": "purchase"
      },
      {
        "name": "view"
      }
    ],
    "num": 5
  }
}
```

The same happens if i define
```
"mirrorType": "localfs" and
"mirrorContainer": "/tmp", #Or any other folder
```

## Insert command

*/engines/freq_purchase_together/imports?import_path=/data/FreqPurchaseTogetherItems.json*

## Why bother? 

We are only inserting events via files. We have a consumer that appends events to a file and after a certain threshold, it triggers an insert command to harness. We are doing this to avoid making a request for every single event. I think it would be nice to use Harness only via the API REST, without going through a manually folder creation.

Thanks for reading!

**Comment by pferrel** [comment]
This is a bug, the work around is to create the leaf directory as you did.

Fixed in the develop branch to be released in Harness v0.6.0
