### ISSUE TITLE
Next step after install?

### ISSUE THREAD

**Issue by Charuru** [actionml/harness#263]
I'm following: https://actionml.com/docs/harness_container_guide

Did: `git clone https://github.com/actionml/harness-docker-compose.git && cd harness-docker-compose && cp .env.sample .env && docker-compose up -d --build`

Now what? The documentation doesn't lead to anything further. How do I create an engine? Is there an example engine? Or is the engine already part of the container?

**Comment by lordk911** [comment]
after install with docker-compose I login container harness-cli , and run the example with : 
`root@f8d52771f7a5:/harness-cli# ./examples/ur/local-ur-integration-test.sh harness 9090`
when step to Training a new model , it's faild with error:

```
08:08:56.233 INFO  connection        - Closed connection [connectionId{localValue:11, serverValue:11}] to mongo:27017 because the pool has been closed.
08:09:53.005 ERROR NetworkClient     - Node [172.31.49.150:9200] failed (org.apache.commons.httpclient.ConnectTimeoutException: The host did not accept the connection within timeout of 60000 ms); no other nodes left - aborting...
08:09:53.006 ERROR URAlgorithm       - Spark computation failed for engine test_ur with params {{"engineId":"test_ur","engineFactory":"com.actionml.engines.ur.UREngine","sparkConf":{"master":"local","spark.driver.memory":"4g","spark.executor.memory":"4g","spark.serializer":"org.apache.spark.serializer.KryoSerializer","spark.kryo.registrator":"org.apache.mahout.sparkbindings.io.MahoutKryoRegistrator","spark.kryo.referenceTracking":"false","spark.kryoserializer.buffer":"300m","es.index.auto.create":"true","spark.es.index.auto.create":"true","es.nodes":"172.31.49.150","spark.es.nodes":"172.31.49.150"},"algorithm":{"indicators":[{"name":"purchase"},{"name":"view"},{"name":"category-pref"}],"num":4}}}
org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot detect ES version - typically this happens if the network/Elasticsearch cluster is not accessible or when targeting a WAN/Cloud instance without the proper setting 'es.nodes.wan.only'
```
 I don't know what the ip:172.31.49.150 is .

**Comment by pferrel** [comment]
Those instructions give you a running server, read he rest of the docs. 

Maybe start here: https://actionml.com/docs/h_ur_quickstart if you are a user of the Universal Recommender.
