### ISSUE TITLE
Spark Exception: A master URL must be set in your configuration

### ISSUE THREAD

**Issue by blinder** [actionml/harness#264]
Steps to reproduce (version 0.5.2-SNAPSHOT)

1. Create an engine (`POST /engines`)
2. Add event data to created engine (`POST /engines/my-engine-id/events`)
3. Train on data (`POST /engines/my-engine-id/jobs`)

Result:
```
23:46:25.618 INFO  ActorSystemImpl   - Complete: HttpMethod(POST):http://localhost:9090/engines/test-test-org/jobs -> 200 OK [54 ms.]
23:46:25.867 INFO  SparkContext      - Running Spark version 2.3.3
23:46:26.033 WARN  NativeCodeLoader  - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
23:46:26.094 ERROR SparkContext      - Error initializing SparkContext.
org.apache.spark.SparkException: A master URL must be set in your configuration
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:367)
	at com.actionml.core.spark.SparkContextSupport$$anonfun$1.apply(SparkContextSupport.scala:132)
	at com.actionml.core.spark.SparkContextSupport$$anonfun$1.apply(SparkContextSupport.scala:119)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Engine configuration:
```json
{
  "engineId": "my-engine-id",
  "engineFactory": "com.actionml.engines.ur.UREngine",
  "sparkConf": {
    "spark.serializer": "org.apache.spark.serializer.KryoSerializer",
    "spark.kryo.registrator": "org.apache.mahout.sparkbindings.io.MahoutKryoRegistrator",
    "spark.kryo.referenceTracking": "false",
    "spark.kryoserializer.buffer": "300m",
    "spark.executor.memory": "3g",
    "spark.driver.memory": "3g",
    "spark.es.index.auto.create": "true",
    "spark.es.nodes": "localhost",
    "spark.es.nodes.wan.only": "true"
  },
  "algorithm":{
    "indicators": [
      {
        "name": "purchase"
      },{
        "name": "email_open"
      }, {
        "name" : "email_click"
      }, {
        "name" : "content_click"
      }, {
        "name" : "like"
      }, {
        "name" : "rsvp"
      }, {
        "name" : "watch"
      }
    ]
  }
}
```

Not sure what I'm missing here, but everything builds fine, starts up, engines are created, event data gets written to MongoDB. Seems there's some missing pieces here.

**Comment by attomos** [comment]
@blinder how did you solve the issue?

**Comment by andreyshikov** [comment]
@blinder looks like your `sparkConf` section lacks `master` parameter.
spark conf - http://spark.apache.org/docs/2.3.4/configuration.html#application-properties
master values - http://spark.apache.org/docs/2.3.4/submitting-applications.html#master-urls


cc: @attomos

**Comment by attomos** [comment]
Got it. Thanks.

**Comment by blinder** [comment]
> @blinder how did you solve the issue?

so yes, my configuration was incomplete, however the real issue i had was that i was trying to index data that did not have entries for all indicators, which I think is a bit odd, but I do understand it. 

the reason why that happened is that my data sample is all over the place, in that we have lots of different types of indicators (as shown in my snippet) but there wouldn't always be data available for an indicator. 

and again i do understand the problem, and i adjusted our data model to only have one indicator, in that only our own database needs to know what type of action was performed (an email click versus a video view or whatever), and we can adjust the weights for own use cases and the harness doesn't need to be that aware of our own stuff. 

what would maybe be useful is something in the documentation about this and maybe some kind of pre-commit check for this condition (having data for every indicator) so an informed exception can be thrown. i don't know, just something i thought about.
