### ISSUE TITLE
Timeout warning when creating a user, using auth

### ISSUE THREAD

**Issue by pferrel** [actionml/harness#27]
The following appears in logs when creating a user using auth:

```
15:01:05.050 WARN  ActorSystemImpl   - HTTP header 'Timeout-Access: <function1>' is not allowed in requests
15:01:05.077 INFO  ActorSystemImpl   - Complete: HttpMethod(POST):http://localhost:9090/auth/users -> 200 OK [65 ms.]
```

**Comment by andreyshikov** [comment]
looks like it's akka-http bug https://github.com/akka/akka-http/issues/64

**Comment by pferrel** [comment]
I don't understand what you are you saying. Is this still a bug? Was the fix wrong?

**Comment by andreyshikov** [comment]
Fix is not about ` HTTP header 'Timeout-Access: <function1>' is not allowed in requests`, looks like I just confused this issue number with another

**Comment by pferrel** [comment]
@andreyshikov is this fixed?

**Comment by andreyshikov** [comment]
not yet, made https://github.com/actionml/harness/pull/54 for it

**Comment by pferrel** [comment]
fixed
