### ISSUE TITLE
ElasticSearch Authentication not available through environment variables

### ISSUE THREAD

**Issue by joetex** [actionml/harness#275]
Hello,

Looking at the source code in ElasticSearchSupport.scala:
https://github.com/actionml/harness/blob/42d660c49332c88d7681e4c296ea1967e067ab2e/rest-server/core/src/main/scala/com/actionml/core/search/elasticsearch/ElasticSearchSupport.scala#L594

```scala
      if (config.hasPath("elasticsearch.auth")) {
        val authConfig = config.getConfig("elasticsearch.auth")
        builder.setHttpClientConfigCallback(new BasicAuthProvider(
          authConfig.getString("username"),
          authConfig.getString("password")
        ))
      }
```

This only allows Elastic Search authentication through application.conf.  Could this be changed to use `Properties.envOrElse`, so that it will work on the Docker Compose setup?  

I would suggest the names that match elasticsearch container:
`ELASTIC_USERNAME`
`ELASTIC_PASSWORD`

Thanks,

Joel

**Comment by sbohner14335** [comment]
Hello, we are having the same issue where we need authentication.

Could we please have this implemented?

**Comment by andreyshikov** [comment]
> This only allows Elastic Search authentication through application.conf.
you also can set|override application.conf with command line params. It depends on how you run harness, but this https://groups.google.com/g/scala-user/c/4lpS1KX9Zx0 discussion may be helpful
