### ISSUE TITLE
Harness Python SDK (maybe java too) revoke and grant allow only one resource permission

### ISSUE THREAD

**Issue by pferrel** [actionml/harness#29]
a user-id should be able to have admin for all resources or client for any number. Adding permission for several resources even it they are enumerated one at a time should be supported.

No required for first release.

**Comment by pferrel** [comment]
@andreyshikov this is fixed, right?

**Comment by andreyshikov** [comment]
> this is fixed, right?

@pferrel no, permissions can be granted to concrete resourceId or all (*)

**Comment by pferrel** [comment]
I'm pretty sure you can "grant" permission to many engineIds for one client userId. No?

**Comment by andreyshikov** [comment]
no, one to one

**Comment by pferrel** [comment]
Why to we have `harness grant...`? Since Users get a permission when created they would never be able to get another? This is a major oversight. One tenant should be able use any number of engine instances in `client`mode.

**Comment by andreyshikov** [comment]
“1 to 1” at the API level, not DB level

**Comment by pferrel** [comment]
We are talking about a functional question not API. 

> Adding permission for several resources even if they are enumerated one at a time should be supported

This means adding one at a time from the CLI is ok as long as many permissions can be attached to one User and I was sure this is supported.

**Comment by andreyshikov** [comment]
> This means adding one at a time from the CLI is ok as long as many permissions can be attached to one User and I was sure this is supported.

yes, if you'll add resourceIds one by one, it will work

**Comment by pferrel** [comment]
This is no longer an issue. Adding engine/resourceIds one at a time is perfectly acceptable for now.
