### ISSUE TITLE
`harness stop` does not always work

### ISSUE THREAD

**Issue by pferrel** [actionml/harness#58]
`harness stop` which uses `cat ${PIDFILE} | xargs kill` does not always work. I have waited a long time and eventually must `kill -9 ...`.

For now we can tell if the stop does not succeed by checking with `jps` and printing a warning. But the real fix is unknown. This seems to have something to do with the Contextual Bandit since it is that integration test that has trouble. This in turn may mean it is a VW integration problem, not sure.

**Comment by pferrel** [comment]
added code in harness-stop to `kill -9` if the first attempt does not kill after waiting for some time. This may not be right, if there is something other than timing causing the first kill to fail.

**Comment by pferrel** [comment]
`kill -9 ...` seems too dangerous, so removed it. We need to see why stop doesn't work sometimes.

**Comment by pferrel** [comment]
This seems to be a problem stopping the contextual bandit. When an instance is running harness consistently fails to stop. Checks are put in the integration tests, which will fail consistently now.

**Comment by dennybaa** [comment]
@pferrel reworked stop/start scripts let's see how it gets from now on with 0.4.0 when the ci branch is merged.
