### ISSUE TITLE
Engine Update exception

### ISSUE THREAD

**Issue by pferrel** [actionml/harness#97]
1) harness add examples/data/ur_nav_hinting.json
2) harness update  examples/data/ur_nav_hinting.json

You get an exception in MongoDao. This blocks being able to test updates that change config since it doesn't work even when config is not changed.

```
15:30:34.319 ERROR OneForOneStrategy - Can't update collection harness_meta_store.engines with filter WrappedArray((engineId,ur_nav_hinting)) and value Document((engineFactory,BsonString{value='com.actionml.engines.urnavhinting.URNavHintingEngine'}), (params,BsonString{value='{
  "engineId" : "ur_nav_hinting",
  "engineFactory" : "com.actionml.engines.urnavhinting.URNavHintingEngine",
  "mirrorContainer" : "/tmp/mirrors",
  "mirrorType" : "localfs",
  "sparkConf" : {
    "master" : "local",
    "spark.driver-memory" : "4g",
    "spark.executor-memory" : "4g",
    "spark.serializer" : "org.apache.spark.serializer.KryoSerializer",
    "spark.kryo.registrator" : "org.apache.mahout.sparkbindings.io.MahoutKryoRegistrator",
    "spark.kryo.referenceTracking" : "false",
    "spark.kryoserializer.buffer" : "300m",
    "es.index.auto.create" : "true"
  },
  "algorithm" : {
    "comment" : "may not need indexName and typeName, derive from engineId? but nowhere else to get the RESTClient address",
    "esMaster" : "es-node-1",
    "blacklist" : [
    ],
    "indicators" : [
      {
        "name" : "nav-event"
      },
      {
        "name" : "search-terms"
      },
      {
        "name" : "content-pref"
      }
    ],
    "availableDateName" : "available",
    "expireDateName" : "expires",
    "dateName" : "date",
    "num" : 6
  }
}'}))
```

**Comment by pferrel** [comment]
I have only tested this on 0.4.0-snapshot

**Comment by pferrel** [comment]
This is nasty because it leaves the DB in a bad state with 2 records with the same engineId.

We should refactor MongoAdministrator to use case classes for engine persistence and the engineId as the unique `_id` instead of a Mongo `ObjectId`. This will enforce that there cannot be 2 with the same engineId by throwing an error somewhere else. 

I will create an enhancement issue for this refactor.

**Comment by pferrel** [comment]
Oh, I saw this mistake and fixed it the same way in 0.4.0-snapshot

@andreyshikov does this exist in 0.3.0-RC2? It does not need a codec because it uses Documents. If not then close this as fixed

**Comment by andreyshikov** [comment]
> It does not need a codec because it uses Documents

yeah, mongo driver can deal with Documents without any codecs

**Comment by andreyshikov** [comment]
looks fixed
