### ISSUE TITLE
Add DAO annotation for a field that is used for the "id" of the collection

### ISSUE THREAD

**Issue by pferrel** [actionml/harness#99]
Assuming a case class is used to store data in a collection, allow one field to be used as the unique id by annotating it with @Id basically following what Morphia does with annotations, which in turn follows some standard applied to Java use of DB (can't remember which one)

This is very important because many case classes have been using `_id` to define the key in a case class and not sure that is still followed not that we are not using Salat & Casbah.

**Comment by andreyshikov** [comment]
looks fixed @pferrel
